[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "base_td"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []


[tool.hatch.version]
path = "__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["."]


[tool.hatch.build.targets.wheel.sources]
"" = "base_td"





