[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["openNucleome"]
namespaces = false

[project]
name = "openNucleome"
version = "1.2.0"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy", 
    "pandas", 
    "scipy",
    "scikit-learn",
    "mdtraj", 
    "MDAnalysis", 
    "OpenMM", 
]

[project.urls]
Homepage = "https://github.com/ZhangGroup-MITChemistry/OpenNucleome"

[tool.setuptools]
include-package-data = true
