[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

[project]
name = "python-project-manager"
version = "0.2.0"

[project.scripts]
ppm = "python_project_manager.app:cli"
