[tool.poetry]
name = "conmasd"
version = "0.1.4"
description = "GitHub Action Self-hosted Runner Operator for Docker"
authors = ["Kyosuke Miyamura <ask@386.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
docker = "^7.0.0"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
cryptography = "^42.0.5"
jwt = "^1.3.1"
pydantic = "^2.6.4"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
conmasd = "conmasd.cli:main"
