[tool.poetry]
name = "kobble-admin"
version = "1.1.0"
description = "Offical SDK to perform privileged operations on your Kobble app"
authors = ["Aurelien Brabant <aurelien@agentlabs.dev>"]
readme = "README.md"
packages = [{ include = "kobble_admin" }]

[tool.poetry.dependencies]
python = "^3.11"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
twine = "^5.0.0"
toml-cli = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
