- hosts: '{{ hosts_name }}'
  tasks:
    - name: create user
      import_tasks: ../create_user.yml
      when: ansible_user_uid == 0

    - name: install ha
      import_tasks: task_ha.yml
      when: ansible_user_uid == 0

    - name: message
      debug:
        msg:
        - "[ASCEND]not support installing ha by non-root user, please switch to root user"
      when: ansible_user_uid != 0

    - name: fail if not root
      fail:
        msg: "[ASCEND]can not install with non-root"
      when: "'ha' in ansible_run_tags and ansible_user_uid != 0"

