[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "imy"
version = "0.1.4"
description = ""
authors = ["Jakob Pinterits <jakob.pinterits@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
json5 = { version = "^0.9.22", optional = true }
motor = { version = "^3.3.2", optional = true }
uniserde = { version = "^0.3.12", optional = true }
introspection = { version = "^1.7.12", optional = true }


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pre-commit = "^3.1.1"

[tool.isort]
profile = "black"
