[project]
name = "ECAPYbara"
version = "0.0.1"
authors = [
    { name="Nicholas Rejack", email="nrejack@users.noreply.github.com"},
]
description = "Elementary Computational Automata for PYthon"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Artistic Software",
]

[project.urls]
Homepage = "https://github.com/nrejack/ecapybara"
Issues = "https://github.com/nrejack/ecapybara/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "/img",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ecapybara"]

