[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "xmltest"
authors = [{name = "Mark Canterbury", email = "markc@tencastle.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">= 3.7"
dependencies = ["xmlschema >= 2"]

[project.scripts]
xmltest = "xmltest:xmltest_console"

[project.optional-dependencies]
test = [
    "pytest"
]

testpaths = [
    "tests",
]