[build-system]
requires = ["hatchling", "pygame"]
build-backend = "hatchling.build"

[project]
name = "PygameToolsBox"
version = "1.0.1"
authors = [
  { name="FranckSix", email="francksix@gmail.com" },
]
description = "Library for manage sprite sheet, and pallax background"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/FranckSix/PygameSpriteTools"
Issues = "https://github.com/FranckSix/PygameSpriteTools/issues"