[tool.poetry]
name = "pydeepsar"
version = "1.0.2"  # semantic-release
description = "This Project aims to ..."
authors = ["Islam Mansour <is3mansour@gmail.com>"]
packages = [
  {include = "pydeepsar"},
]
license = "GNU General Public License v3"
exclude = [
  ".git/*",
  ".env*",
]
include = ["pydeepsar/py.typed"]

[tool.poetry.dependencies]
python = "<3.12,>=3.9.1"
tensorflow = "<=2.17.0,>=2.14"
scipy = ">=1.11.3"
rioxarray = "<0.15.1"
seaborn = "^0.13.2"
netcdf4 = "^1.6.5"
scikit-learn = "^1.4.1.post1"
tf-keras = ">=2.16,<3.0"

[tool.poetry.group.dev.dependencies]
urllib3 = "<2"  # fix poetry issues
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
coverage = "^7.2.7"
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"
flake8 = "^7.0"
ruff = "^0.3.2"
mypy = "^1.3.0"
bandit = "^1.7.5"
pydocstyle = "^6.3.0"
vulture = "^2.7"
mccabe = "^0.7.0"
# if you want to use docker-compose from your system, remove compose-go here
compose-go = "^2.18.1"
ipython = "<8"
ipykernel = ">=6.0.0"
importlib-metadata = "^6.5.1"
makim ="^1.8.3"
nbqa = {extras = ["toolchain"], version = "^1.8.4"}
prettier = "^0.0.7"



[tool.poetry.group.docs.dependencies]
pydata-sphinx-theme = "^0.15.2"
nbsphinx = "^0.9.2"
sphinx = "^6.2.1"
sphinx-design = "^0.5.0"
matplotlib = "^3.8.3"
numpydoc = "^1.6.0"
jupytext = "^1.16.1"
myst-nb = "^1.0.0"
pooch = "^1.8.1"
jupyterlite-sphinx = ">=0.12.0"
jupyterlite-pyodide-kernel = "^0.2.3"
sphinx-rtd-theme = "^1.2.2"
pandoc = "^2.3"
myst-parser = "^1.0.0"
esbonio = "^0.16.4"
sphinx-autoapi = "^3.0.0"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 79
target-version = ["py38"]
force-exclude = '''(?x)(
    docs/*
  | .*\\.egg-info
)'''  # TOML's single-quoted strings do not require escaping backslashes

[tool.isort]
ensure_newline_before_comments = true
line_length = 79
multi_line_output = 3
include_trailing_comma = true
skip_glob = ["docs/*", "*.egg-info"]

[tool.bandit]
exclude_dirs = ["tests"]
targets = "./"

[tool.vulture]
exclude = ["tests"]
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 80
paths = ["./"]
sort_by_size = true
verbose = false

[tool.ruff]
line-length = 79
force-exclude = true
src = ["./"]
exclude = [
  'docs',
]
lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "D",   # pydocstyle
  "YTT", # flake8-2020
  "RUF", # Ruff-specific rules
  "I001",  # isort
]
lint.fixable = ["I001"]
# Use a single line between direct and from import
lint.isort.lines-between-types = 1
lint.pycodestyle.ignore-overlong-task-comments = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.11"
files = ["pydeepsar", "tests"]
exclude = [
    "docs/_build",
]
check_untyped_defs = true
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
