[tool.poetry]
name = "pytest_energy_reporter"
version = "0.4.2"
authors = [
  "Delano Flipse <delanoflipse@gmail.com>",
]
maintainers = [
  "Delano Flipse <delanoflipse@gmail.com>",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Framework :: Pytest",
]
description = "An energy estimation reporter for pytest"
readme = "readme.md"
license = "license.txt"
keywords = ["pytest", "energy", "reporter"]

[tool.poetry.urls]
Homepage = "https://github.com/delanoflipse/pytest-energy-reporter"
Documentation = "https://github.com/delanoflipse/pytest-energy-reporter"
Repository = "https://github.com/delanoflipse/pytest-energy-reporter"
"Bug Tracker" = "https://github.com/delanoflipse/pytest-energy-reporter/issues"

[tool.poetry.plugins."pytest11"]
pytest_energy_reporter = "pytest_energy_reporter.plugin"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.1.1"
numpy = "1.26.4"
optuna = "3.5.0"
pandas = "2.2.0"
scipy = "1.12.0"
xgboost = "2.0.3"
psutil = "5.9.8"
pyarrow = "15.0.0"
scikit-learn = "1.4.1.post1"
statsmodels = "0.14.1"

[tool.poetry.group.dev.dependencies]
setuptools = "^69.2.0"

[tool.poetry.group.temp.dependencies]
numpy = "1.26.4"
optuna = "3.5.0"
pandas = "2.2.0"
scipy = "1.12.0"
xgboost = "2.0.3"
psutil = "5.9.8"
pyarrow = "15.0.0"
scikit-learn = "1.4.1.post1"
statsmodels = "0.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
