[project]
name = "mosaik-mango"
description = "An adapter to integrate a mango simulation into mosaik"
authors = [
  { name = "Eike Schulte", email = "eike.schulte@offis.de" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "mosaik-api-v3 ~= 3.0.4",
  "loguru ~= 0.7.2",
]
dynamic = ["version"]

[project.optional-dependencies]

[tool.hatch.build.targets.wheel]
packages = ["src/mosaik_components"]

[tool.hatch.build.targets.sdist]
packages = ["src/mosaik_components"]

[tool.hatch.envs.default]
dependencies = [
  "mosaik ~= 3.2.0",
  "mango-agents ~= 1.1.3",
]

[tool.hatch.envs.test]
dependencies = [
  "pytest ~= 7.3.1",
  "pytest-watch ~= 4.2.0",
  "pyarrow ~= 15.0.0",
]

[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"

[[tool.hatch.envs.test.matrix]]
# Remember to also change .gitlab-ci.yml if you change the Python versions here
python = ["3.9", "3.11"]
mosaik-beta = ["mosaik-stable", "mosaik-beta"]

[tool.hatch.envs.test.overrides]
matrix.mosaik-beta.dependencies = [
  { value = "mosaik == 3.2.0", if = ["mosaik-stable"] },
  { value = "mosaik == 3.3.0.b1", if = ["mosaik-beta"] },
]

[tool.hatch.envs.docs]
dependencies = [
  "sphinx ~= 7.2.5",
]

[tool.pytest.ini_options]
pythonpath = ["tests"]
addopts = [
  "--import-mode=importlib"
]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py39"

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
ignore = ["TRY", "EM"]  # maybe reconsider

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["INP001"]
"tests/**/*" = ["S101", "T201"]
"__init__.py" = ["PLC0414"]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false

[tool.hatch.version]
source = "vcs"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
