[tool.poetry]
name = "kwwutils"
version = "0.1.0"
description = "General utilities working with Ollama and Langchain"
authors = ["Kenneth Wong <kennethwork101@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.13"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
