[tool.poetry]
name = "anybt"
version = "1.1.0"
description = "An Open Sourced Decentralized BitTorrent Search Engine"
authors = ["j2qk3b"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "2.29.0"
rich = "^13.7.1"

[tool.poetry.scripts]
anybt = "anybt:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
