# Settings
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "udk"
version = "0.0.6"
authors = [
  { name="Johniscool76", email="isanoob1897@outlook.com" },
]
description = "A collection of tools"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Bruceli-iscool/Utilities"
Issues = "https://github.com/Bruceli-iscool/Utilities/issues"