# Project config
[project]

# Distribution name of the package
name = 'ctms-utils'

# Package version
version = '0.3.1'

# Package description
description = 'Binary utilities for working with embedded object files'

# Python requirement
requires-python = '>=3.12.2'

# Package authors
authors = [
	{ name='Colton Murphy', email='cmurp77@gmail.com' },
]

# Package classifiers
classifiers = [
	'Programming Language :: Python :: 3',
	'Operating System :: Microsoft :: Windows :: Windows 10',
]

# Package discovery
[tool.setuptools.packages.find]

# Packages root dir
where = ['packages']

# Package data config
[tool.setuptools.package-data]

# Include shared libraries
'ctms.utils' = ['*.dll']