[tool.poetry]
name = "hr-dataset"
version = "0.1.4"
description = ""
authors = ["Christian Frost <terminated@ramboll.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.1"
ipykernel = "^6.29.3"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
