[project]
name = "3m"
version = "0.1.1"
description = "3m"
authors = [
    { name = "yyh", email = "yangchichi@126.com" },
]
dependencies = [
    "streamlit>=1.32.2",
    "llama-index>=0.10.23",
    "llama-index-llms-openai-like>=0.1.3",
    "camelot-py==0.11.0",
    "ghostscript>=0.7",
    "streamlit-echarts>=0.4.0",
    "llama-index",
    "ghostscript",
    "numpy~=1.24.4",
    "pandas~=1.5",
    "streamlit>=1.25.0",
    "streamlit-option-menu>=0.3.6",
    "streamlit-antd-components>=0.1.11",
    "streamlit-chatbox>=1.1.6",
    "transformers>=4.39.1",
    "pypdf2",
    "nvitop==1.2.0",
    "langchain",
    "faiss-cpu==1.7.2",
    "openai",
    "parsr-client",
    "streamlit-extras",
    "streamlit-javascript",
    "streamlit-echarts",
    "stqdm",
    "matplotlib",
    "scikit-learn",
    "wordcloud",
    "python-dotenv",
    "loguru",
    "omegaconf==2.1.1",
    "PyMuPDF",
    "camelot-py",
    "tabulate",
    "opencv-python",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
