[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true
name = "catch-me"
version = "0.3.0"
description = "ğŸ Catch me if you can!ğŸ°"
authors = ["Oleksis Fraga <oleksis.fraga@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/oleksis/Tkinter"
keywords = ["tk", "python", "ui", "game"]
packages = [
    { include = "app.py" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
catch-me = 'app:main'
