[project]
name = "crunchyroll-api_jbsky"
version = "0.0.1"
authors = [
  { name="jbsky", email="webmaster@jbsky.fr" },
]
description = "Crunchyroll API Python interface"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jbsky/crunchyroll-api"
Issues = "https://github.com/jbsky/crunchyroll-api/issues"