[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alxhttp"
version = "0.9.17"
authors = [
  { name="Alexander Macdonald", email="alex@alexmac.cc" },
]
description = "A better base server for AioHTTP"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'aiohttp ~= 3.9',
]

[project.optional-dependencies]
xray = [ 
  'aws-xray-sdk ~= 2.13' 
]

[project.urls]
Homepage = "https://github.com/alexmac/alxhttp"


