[tool.poetry]
name = "wifi-connection"
version = "0.1.1"
description = ""
authors = ["grace tung <grace_tung@asus.com>"]
readme = "README.md"

[tool.poetry.scripts]
wifi-connection = "wifi_connection.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.9.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
