[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai4ml"
version = "0.0.1"
authors = [
    { name = "Yuxiang Wu", email = "yuxiang@weco.ai" },
]
description = "Python package for using Weco's service"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
