[project]
name = "TBFLib"
version = "1.2"
description = "That's Formula module for python."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "fly-toribird", email = "fly-toribird@outlook.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = []

[project.urls]
Repository = "https://github.com/fly-toribird/TBF"
