[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Calculator.mehr"
authors = [{name = "Ramin Baghaei Mehr", email = "ramin.mehr@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/Ramin-Mehr"
